trailblazer/mainapp/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^signup/',views.signupaction,name='signupaction'),
    url(r'^projectideas',views.projectideas,name='projectideas'),
    url(r'^preview',views.prerequisitesview,name='preview'),
    url(r'^preweb',views.preweb,name='preweb'),
    url(r'^madview',views.madview,name='madview'),
    url(r'^premlview',views.premlview,name='premlview'),
    url(r'^cseview',views.cseview,name='cseview'),
    url(r'^eceview',views.eceview,name='eceview'),
    url(r'^prevlsi',views.prevlsiview,name='prevlsi'), 
    url(r'^embedded',views.embeddedview,name='embedded'), 
    url(r'^preiot',views.iotview,name='preiot'),
    url(r'^autocad',views.autocadview,name='autocad'),
    url(r'^revit',views.revitview,name='revit'),
    url(r'^sketchup',views.sketchupview,name='sketchup'),
    url(r'^contact',views.contact,name='contact'),
    url(r'^feed',views.feedbackview,name='feed'),
    url(r'^cseab/',views.cseabstract,name='cseab'),
    url(r'^civilab/',views.civilabstract,name='civilab'),
    url(r'^mechab/',views.mechabstract,name='mechab'),
    url(r'^csepro/',views.cseproject,name='csepro'),
    url(r'^ecepro/',views.eceproject,name='ecepro'),
    url(r'^civilpro/',views.civilproject,name='civilpro'),
    url(r'^mechpro/',views.mechproject,name='mechpro'),
    url(r'^about/',views.aboutview,name='about'),
]

trailblazer/trailblazer/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from mainapp import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.loginaction,name="loginaction"),
    url(r'mainapp/',include('mainapp.urls')),
    url(r'^home/',views.home,name='home'),
    url(r'^abstract/',views.abstract,name='abstract'),
    url(r'^view/', views.pdf_view,name='view'),

]

trailblazer/mainapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Abstracts(models.Model):  
    name = models.CharField(max_length=50,default='',null=False)  
    
    email = models.EmailField(max_length=50,default='',null=False)  
    project = models.CharField(max_length=50,default='',null=False)  
    abstract = models.TextField(max_length=1000,default='',null=False)   
class Eceabstract(models.Model):  
    Name = models.CharField(max_length=50,default='',null=False)  
    
    Email = models.EmailField(max_length=50,default='',null=False)  
    Project = models.CharField(max_length=50,default='',null=False)  
    Abstract = models.TextField(max_length=1000,default='',null=False)   
class Cseab(models.Model):  
    Name = models.CharField(max_length=50,default='',null=False)  
    
    Email = models.EmailField(max_length=50,default='',null=False)  
    Project = models.CharField(max_length=50,default='',null=False)  
    Abstract = models.TextField(max_length=1000,default='',null=False)   
class Civilabstract(models.Model):  
    Name = models.CharField(max_length=50,default='',null=False)  
    
    Email = models.EmailField(max_length=50,default='',null=False)  
    Project = models.CharField(max_length=50,default='',null=False)  
    Abstract = models.TextField(max_length=1000,default='',null=False)  
class Mechabstract(models.Model):  
    Name = models.CharField(max_length=50,default='',null=False)  
    
    Email = models.EmailField(max_length=50,default='',null=False)  
    Project = models.CharField(max_length=50,default='',null=False)  
    Abstract = models.TextField(max_length=1000,default='',null=False)   
class FeedBack(models.Model):
    Name = models.CharField(max_length=50,default='',null=False)
    Email = models.EmailField(max_length=50,default='',null=False)
    feedback = models.TextField(max_length=1000,default='',null=False)
class Contact(models.Model):
    Name = models.CharField(max_length=50,default='',null=False)
    Email = models.EmailField(max_length=50,default='',null=False)
    Message = models.TextField(max_length=1000,default='',null=False)
class Cseproject(models.Model):  
    Name = models.CharField(max_length=50,default='',null=False)  
    
    Email = models.EmailField(max_length=50,default='',null=False)  
    Project = models.CharField(max_length=50,default='',null=False)  
    Abstract = models.TextField(max_length=1000,default='',null=False)  
class Eceproject(models.Model):  
    Name = models.CharField(max_length=50,default='',null=False)  
    
    Email = models.EmailField(max_length=50,default='',null=False)  
    Project = models.CharField(max_length=50,default='',null=False)  
    Abstract = models.TextField(max_length=1000,default='',null=False)
class Civilproject(models.Model):  
    Name = models.CharField(max_length=50,default='',null=False)  
    
    Email = models.EmailField(max_length=50,default='',null=False)  
    Project = models.CharField(max_length=50,default='',null=False)  
    Abstract = models.TextField(max_length=1000,default='',null=False)  
class Mechproject(models.Model):  
    Name = models.CharField(max_length=50,default='',null=False)  
    
    Email = models.EmailField(max_length=50,default='',null=False)  
    Project = models.CharField(max_length=50,default='',null=False)  
    Abstract = models.TextField(max_length=1000,default='',null=False)       

trailblazer/templates/abstract.html
<html>
{% load staticfiles %}
<head>
<title>Django File Upload - cairocoders</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/abstract1.css' %}">
</head>
<body>
    <a href={% url 'projectideas' %}><input type="button" class="button" value="back"></a>
    <h1>Upload your abstracts</h1>
<div class="container">
  
      
           
            <form class="" action="" method="post" >
                {% csrf_token %}
                <p><label for="id_name"><p>Name:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="name" pattern="^([A-Z]|[a-z])*$" id="id_name" placeholder="Ex:-Jahnavi" required /></p>
                <p><label for="id_email"><p>Email:</p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="email" name="email" id="id_email" pattern="^([a-z]|[0-9])*@gmail.com$" placeholder="Ex:-ekotijahnavi0504@gmail.com" required  /></p>
                <p><label for="id_project"><p>Project:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="project" id="id_project" placeholder="Ex:-library management system" required /></p>
                <p><label for="id_feedback"> <p>Abstract:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label><textarea name="abstract" cols="40" rows="3" required id="id_feedback">
                </textarea></p>

                <button type="submit" class="submit" >Submit abstract</button>
            </form> 
   
          
</div>
<a href=""><button class="refresh">refresh to see feedback</button></a>
    <br><br>
    <div class="feedback">
        {% for instance in ab %}
        
          <div class="name">{{instance.fields.Project}}</div>
           
              
          <div class="feed"><a href="{{instance.fields.Abstract}}">click here to view the abstract</a></div>
        
        {% endfor %}
        </div>
            {% if messages %}
                {% for message in messages %}
                    <small {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</small>
                {% endfor %}
            {% endif %} 
           
   
</body>  
</html>

trailblazer/templates/contact.html
<!DOCTYPE html>
{%load staticfiles %}
<head>
    	<title>Contact Us </title>
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    	<link rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous" href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' >
    	<link rel="stylesheet" type="text/css" href="{% static 'css/contact1.css' %}">
</head>
<body>
   
	
    	<section class="contact">
            <a href="{% url 'home' %}"><input  class="button" type="button" value="home"></a>
    		<div class="content">
    			<h2>Contact Us</h2>
    		</div>
			<div class="msg">
			{% if messages %}
	{% for message in messages %}
		<small {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</small>
	{% endfor %}
{% endif %}
			</div>
    		<div class="container">
    			<div class="contactInfo">
    				<div class="box">
    					<div class="icon"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
    					<div class="text">
    						<h3>Address</h3>
    						<p>RGUKT RK Valley,<br>Idupulapaya,<br>Vempalli<br>Kadapa<br>516330</p>
    					</div>
    				</div>
    				<div class="box">
    					<div class="icon"><i class="fa fa-phone" aria-hidden="true"></i></div>
    					<div class="text">
    						<h3>Phone</h3>
    						<p>9100810469<br>9502836884</p><p>9553209846</p>
    					</div>
    				</div>
    				<div class="box">
    					<div class="icon"><i class="fa fa-envelope" aria-hidden="true"></i></div>
    					<div class="text">
    						<h3>Email</h3>
    						<p>r170829@rguktrkv.ac.in<br>r170415@rguktrkv.ac.in</p><p>r170416@rguktrkv.ac.in</p>
    					</div>
    				</div>
    			</div>
    			<div class="contactForm">
    				<form  action="" method="post">
                        {% csrf_token %}
    					<h2>Send Message</h2>
    					<div class="inputBox">
    						<input type="text" name="name" required="required">
    						<span>Full Name</span>
    					</div>
    					<div class="inputBox">
    						<input type="text" name="email" required="required">
    						<span>Email</span>
    					</div>
    					<div class="inputBox">
    						<textarea required="required" name="message"></textarea>
    						<span>Type Your Message...</span>
                           
    					<div class="inputBox">
							<button type="submit" >Submit</button>
    					</div>
    				</form>
    			</div>
    		</div>
    	</section>
 
</body>
</html>

trailblazer/templates/cseabstract.html
<html>
{% load staticfiles %}
<head>
<title>cse abstracts</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/abstract1.css' %}">
</head>
<body>
    <a href={% url 'projectideas' %}><input type="button" class="button" value="back"></a>
    <h1>Upload your abstracts</h1>
<div class="container">
  
      
           
            <form class="" action="" method="post" >
                {% csrf_token %}
                <p><label for="id_name"><p>Name:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="name" pattern="^([A-Z]|[a-z])*$" id="id_name" placeholder="Ex:-Jahnavi" required /></p>
                <p><label for="id_email"><p>Email:</p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="email" name="email" id="id_email" pattern="^([a-z]|[0-9])*@gmail.com$" placeholder="Ex:-ekotijahnavi0504@gmail.com" required  /></p>
                <p><label for="id_project"><p>Project:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="project" id="id_project" placeholder="Ex:-library management system" required /></p>
                <p><label for="id_feedback"> <p>Abstract:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label><textarea name="abstract" cols="40" rows="3" required id="id_feedback">
                </textarea></p>

                <button type="submit" class="submit" >Submit </button>
            </form> 
   
          
</div>
{% if messages %}
{% for message in messages %}
    <small {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</small>
{% endfor %}
{% endif %} 
<a href=""><button class="refresh">refresh to see feedback</button></a>
    <br><br>
    <div class="feedback">
        {% for instance in ab %}
        
          <div class="name">{{instance.fields.Project}}</div>
           
              
          <div class="feed"><a href="{{instance.fields.Abstract}}">click here to view the abstract</a></div>
        
        {% endfor %}
        </div>
         
           
   
</body>  
</html>

trailblazer/templates/cseproject.html
<html>
{% load staticfiles %}
<head>
<title>cse abstracts</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/abstract1.css' %}">
</head>
<body>
    <a href={% url 'cseview' %}><input type="button" class="button" value="back"></a>
    <h1>Upload your Projects</h1>
<div class="container">
  
      
           
            <form class="" action="" method="post" >
                {% csrf_token %}
                <p><label for="id_name"><p>Name:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="name" pattern="^([A-Z]|[a-z])*$" id="id_name" placeholder="Ex:-Jahnavi" required /></p>
                <p><label for="id_email"><p>Email:</p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="email" name="email" id="id_email" pattern="^([a-z]|[0-9])*@gmail.com$" placeholder="Ex:-ekotijahnavi0504@gmail.com" required  /></p>
                <p><label for="id_project"><p>Project:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="project" id="id_project" placeholder="Ex:-library management system" required /></p>
                <p><label for="id_feedback"> <p>Abstract:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label><textarea name="abstract" cols="40" rows="3" required id="id_feedback">
                </textarea></p>

                <button type="submit" class="submit" >Submit</button>
            </form> 
   
          
</div>
{% if messages %}
{% for message in messages %}
    <small {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</small>
{% endfor %}
{% endif %} 
<a href=""><button class="refresh">refresh to see projects</button></a>
    <br><br>
    <div class="feedback">
        {% for instance in ab %}
        
          <div class="name">{{instance.fields.Project}}</div>
           
              
          <div class="feed"><a href="{{instance.fields.Abstract}}">click here to view the abstract</a></div>
        
        {% endfor %}
        </div>
          
           
   
</body>  
</html>

trailblazer/templates/eceproject.html
<html>
{% load staticfiles %}
<head>
<title>cse abstracts</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/abstract1.css' %}">
</head>
<body>
    <a href={% url 'eceview' %}><input type="button" class="button" value="back"></a>
    <h1>Upload your Projects</h1>
<div class="container">
  
      
           
            <form class="" action="" method="post" >
                {% csrf_token %}
                <p><label for="id_name"><p>Name:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="name" pattern="^([A-Z]|[a-z])*$" id="id_name" placeholder="Ex:-Jahnavi" required /></p>
                <p><label for="id_email"><p>Email:</p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="email" name="email" id="id_email" pattern="^([a-z]|[0-9])*@gmail.com$" placeholder="Ex:-ekotijahnavi0504@gmail.com" required  /></p>
                <p><label for="id_project"><p>Project:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="project" id="id_project" placeholder="Ex:-library management system" required /></p>
                <p><label for="id_feedback"> <p>Abstract:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label><textarea name="abstract" cols="40" rows="3" required id="id_feedback">
                </textarea></p>

                <button type="submit" class="submit" >Submit</button>
            </form> 
   
          
</div>
{% if messages %}
{% for message in messages %}
    <small {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</small>
{% endfor %}
{% endif %} 
<a href=""><button class="refresh">refresh to see Projects</button></a>
    <br><br>
    <div class="feedback">
        {% for instance in ab %}
        
          <div class="name">{{instance.fields.Project}}</div>
           
              
          <div class="feed"><a href="{{instance.fields.Abstract}}">click here to view the abstract</a></div>
        
        {% endfor %}
        </div>
        
           
   
</body>  
</html>

trailblazer/templates/embedded.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>prerequisites for embeddedsystems</title>
    <link rel='stylesheet' href="{% static 'css/embedded.css' %}">
</head>
<body>
    <a href="{% url 'preview' %}"><input  class="button" type="button" value="back">
    </a>
    <h1>Embedded  Systems</h1>
    <div class="center1">
        <img class="back" src={% static "images/em3.jpeg"%}>
        <p class="p">An embedded system is a computer system with a combination of a computer processor, computer memory, input/output peripheral devices that perform the task assigned. These systems are generally found in large mechanical and electrical projects. These systems control physical operations in a large structure and hence has a very large application in the field of electrical run devices.
        </p>
    </div>
    <div class="center1">
        <img class="back" src={% static "images/em2.jpeg"%}>
        <h2>What comes under Embedded Systems?</h2>
        <p class="p">
            Having known what an embedded system is, it is obvious for anyone to be curious about its field of application. So, here are some of the devices which come under embedded systems:
            
            <br>Computers
            <br>Mobile phones
            <br>Tablets
            <br>Laptops
            <br>Digital electronic systems
            <br>Video game consoles
            <br>Dishwashers
            <br>Washing machines
            <br>Medical imaging
            <br>Bank lockers
            <br>And many other electrical and electronic devices come under an embedded system.
            <br>As every electronic device would be having, even an embedded system has hardware and software components.
                <br>Some of the hardware stuff includes:
            
            <br>Timers, memory devices, Central processing unit, output circuits, power supply kit, serial communication parts, etc.
        </p>
    </div>
    <div class="section1">
   
        <div class="center">
            <h2 id="apache">How does an embedded system work?</h2>
            <img class="img-deg" src={% static "images/em.webp" %}>
            <p>Embedded systems deploy the integration of software on a motherboard with hardware in an embedded environment to perform a particular task. The three main steps involved in the working of any embedded system are:

                <br><span>1.Input- </span>The first step is taking input from the user/environment. The input can be user associated in the form of push switches, touch screens, etc. It can also be automatic values collected by sensors like humidity sensors, PIR sensors, etc.
                <br><span>2.Processing-</span>The next step is processing the input to perform the next step. This step involves calculations or algorithms which are performed on the microprocessor or microcontroller.
                <br><span>3.Output- </span>The last and the final step is the output. Based on the results obtained in the previous step the final output is displayed. This output can be in various forms based on the need of the system like the movement of a machine part, results on a screen, etc.</p>
        </div>
    </div>
    <div class="section1">
   
        <div class="center">
            <h2>What are the different types of embedded systems?</h2>
            <img class="img-deg" src={% static "images/em4.jpeg" %}>
            <p>Embedded systems can be classified into four types based on their performance and functional requirements. They are as follows:
                <br><span>1.Real-time Embedded System- </span>These systems perform real-time analysis on the data and focus on quick response in critical situations. The error rate is reduced to a minimal value to avoid faults. Some examples include traffic monitoring systems, a radiation therapy system, etc.
                <br><span>2.Stand-Alone Embedded System- </span>These systems are stand-alone independent devices that are not connected to any external computers for support. These systems take the inputs and process them to operate. Some examples include microwave ovens, digital cameras, etc.
                <br><span>3.Networked Embedded System- </span>These systems are connected over some network to give output to the connected resources. The connections may be wired or wireless depending on the system. Such systems are gaining a lot of popularity these days and are widely used across different domains.
                <br><span>Mobile Embedded System-</span>These systems are small embedded systems with limited applications and memory. Some examples include cellular phones, mp3 players, digital cameras, personal digital assistants, etc.
             </p>
        </div>
    </div>
    <div class="section1">
        
        <div class="center">
            <h2>What programming language is used for embedded systems?</h2>
            <img class="img-deg" src={% static "images/em5.jpeg" %}>
            <p>Although there are a lot of languages that can be used for embedded systems, C programming language is most widely used in embedded systems. C++ and JAVA are other languages that find good use.</p>
                
            <p>C, as we know is one of the oldest and most powerful languages to ever emerge and hence it is an easy choice when it comes to programming in embedded systems. Here are a few reasons why C is chosen over other languages:
                
                <br>It provides low-level access.
                <br>Low memory usage of a compiled C program is a major reason behind the acceptance of C as a best-embedded programming language.
                <br>Statistically typed language- offers a great speed compared to other languages.
                <br>Its loose data typing policy makes it even more suitable for programming.
                <br>The Widespread community provides vast support for embedded systems programming.
                <br>Simple to port the embedded programs from one device to another.
                <br>Although, apart from C, there are many other programming languages that can be used in different stages. Some of those include:
                
                <br><span>C++, JAVA, RUST, PYTHON, ADA, VERILOG, B#, LUA, VHDL, Embedded C++, etc.</span></p>
            <p> Also, here are a few skills required for you to understand embedded systems better:
                
                Knowledge of programming languages like C and C++ at the very least.
                You need to be comfortable with assemble languages and have experience working with LabView.
                Need to have basic knowledge regarding the working of a microcontroller and microprocessor
                n-depth knowledge about Arduino and Raspberry pi</p>
        </div>
    </div>

    <div class="section1">
        <div class="center">
            <h2>Scope of Embedded Systems</h2>
            <img class="img-deg" src={% static "images/em6.jpeg" %}>
            <p>As the number of intelligent devices increase, the scope for this field gradually increases. It has fantastic career prospects due to its large-scale functionality. Some of the fields of applications are:
                
                <br>Quality assurance engineer
                <br>Program management
                <br>Embedded app developer
                <br>Simulation expert
                <br>Sales and marketing engineer
                <br>Companies like SAMSUNG, SONY, TCS, WIPRO, L&T, INTEL, ROBERT BOSCH are top embedded based companies in India.
                
            </p>
        </div>
    </div>
    <div class="section1">
        <div class="center">
            <h2>What are the Kits used for Embedded Project?</h2>
            <img class="img-deg" src={% static "images/em7.jpeg" %}>
            <p>
                The best way to learn something is by doing it and so building a project based on embedded systems domain could be the right way to link up your theoretical knowledge with the practical concepts. For that, you need good kits for your project to run smoothly.
                
                <br>So, here are some of the kits used for building embedded systems projects:
                
               <br>1.Breadboard
                <br>2.LED’s
                <br>3.Arduino Uno
                <br>4.Raspberry pi
                <br>5.HC05 blue-tooth module
                <br>6.Different types of sensors like IR, water flow, etc.
                <br>USB to UART cable
                <br>ESP-8266 Wi-Fi Module
                <br>Resistors
                <br>Batteries</p>
        </div>
    </div>
 
    <div class="section1">
   
        <div class="center">
            <h2>How to Build an Embedded Systems Project?</h2>

            <img class="img-deg" src={% static "images/em8.jpeg" %}>
            <p>So here we come, to the final step, and the most exciting one.
                
                <br>Once you are done with learning different kinds of programming languages and acquiring different sets of skills, it all comes down to the part of the application, wherein you need to apply and build practically without which all the above is useless.
                
               <br> So, to do a project, be it as a 4th year’s final year project or a child prodigy in the field of science, you will need a solid platform to start off with.
                
                <br>One such platform is online, wherein you can sign up for any online course on building projects in a few top trusted websites.
                
               <br> Skyfi Labs is one such excellent platform wherein you can learn a lot of courses and explore the technological world.</p>
        </div>
    </div>
    
</body>
</html>

trailblazer/templates/login.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>login</title>
    <link rel='stylesheet' href="{% static 'css/login2.css' %}">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Rubik:400,700'>
<body>

<h2>Login Form</h2>
{% if form.errors %}
  <p>Username or password are not correct </p>
{% endif %}
<div class="login-form">
<form action="" method="POST" novalidate>
  <h1>Login</h1>
  <div class="imgcontainer">
    <!--<img src="{% static 'images/img2.jpg' %}" alt="" class="avatar">-->
  </div>
  <div class="container">
    <div class="content">
    <div class="input-field">
    <strong>
  {% csrf_token %}
      {% for fm in form %}
        {{fm.label_tag}} {{fm}} {{fm.errors|striptags}}<br><br>
        {% endfor %}
   </strong>
   </div>
   </div>
          <!---
      <label for="uname"><b>Username</b></label>
      <input type="text" placeholder="Enter Username" name="uname" required><br>
  
      <label for="psw"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" required> <br> --> 

    <div class="action">
    <a href={% url 'loginaction' %}> <button class="button">login</button></a>
    <a href={% url 'signupaction' %}><input type="button" class="button" value="newuser"></a><br>
 
   <!---<h1 style="color:#f44336">{{error}}</h1>
    <h1 style="color:#04AA6D">{{info}}</h1>-->
   </div>
  </div>

 
</form>
</div>

</body>
</html>

trailblazer/templates/mechabstract.html
<html>
{% load staticfiles %}
<head>
<title>cse abstracts</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/abstract.css' %}">
</head>
<body>
    <a href={% url 'projectideas' %}><input type="button" class="button" value="back"></a>
    <h1>Upload your abstracts</h1>
<div class="container">
  
      
           
            <form class="" action="" method="post" >
                {% csrf_token %}
                <p><label for="id_name"><p>Name:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="name" pattern="^([A-Z]|[a-z])*$" id="id_name" placeholder="Ex:-Jahnavi" required /></p>
                <p><label for="id_email"><p>Email:</p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="email" name="email" id="id_email" pattern="^([a-z]|[0-9])*@gmail.com$" placeholder="Ex:-ekotijahnavi0504@gmail.com" required  /></p>
                <p><label for="id_project"><p>Project:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label> <input type="text" name="project" id="id_project" placeholder="Ex:-library management system" required /></p>
                <p><label for="id_feedback"> <p>Abstract:</p>&nbsp;&nbsp;&nbsp;&nbsp;</label><textarea name="abstract" cols="40" rows="3" required id="id_feedback">
                </textarea></p>

                <button type="submit" class="submit" >Submit</button>
            </form> 
   
          
</div>
<a href=""><button class="refresh">refresh to see Abstract</button></a>
    <br><br>
    <div class="feedback">
        {% for instance in ab %}
        
          <div class="name">{{instance.fields.Project}}</div>
           
              
          <div class="feed"><a href="{{instance.fields.Abstract}}">click here to view the abstract</a></div>
        
        {% endfor %}
        </div>
            {% if messages %}
                {% for message in messages %}
                    <small {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</small>
                {% endfor %}
            {% endif %} 
           
   
</body>  
</html>